---
title: "R Notebook"
output: html_notebook
library(spatstat)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmap)
library(sf)
library(geojsonio)
library(tmaptools)
EW <- geojson_read("http://geoportal.statistics.gov.uk/datasets/8edafbe3276d4b56aec60991cbddda50_2.geojson", what = "sp")
BoroughMap <- EW[grep("^E09",EW@data$lad15cd),]
qtm(BoroughMap)
summary(BoroughMap)
BNG = "+init=epsg:27700"
BoroughMapBNG <- spTransform(BoroughMap,BNG)
BluePlaques <- geojson_read("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson", what = "sp")
summary(BluePlaques)
BNG = "+init=epsg:27700"
WGS = "+init=epsg:4326"
BluePlaquesBNG <- spTransform(BluePlaques, BNG)
summary(BluePlaquesBNG)
tmap_mode("view")
tm_shape(BoroughMapBNG) +
  tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(BluePlaquesBNG) +
  tm_dots(col = "blue")
BoroughMapBNGSF <- st_as_sf(BoroughMapBNG)
BoroughSF <- BoroughMapBNGSF[BoroughMapBNGSF$lad15nm=="Harrow",]
tm_shape(Borough) +
  tm_polygons(col = NA, alpha = 0.5)
BluePlaquesSub <- BluePlaquesBNG[Borough,]
tmap_mode("view")
tm_shape(Borough) +
  tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
window <- as.owin(Borough)
plot(window)
BluePlaquesSub.ppp <- ppp(x=BluePlaquesSub@coords[,1],y=BluePlaquesSub@coords[,2],window=window)
BluePlaquesSub@coords[,1]
plot(BluePlaquesSub.ppp,pch=16,cex=0.5, main="Blue Plaques Harrow")
plot(density(BluePlaquesSub.ppp, sigma = 500))
plot(density(BluePlaquesSub.ppp, sigma = 1000))
plot(BluePlaquesSub.ppp,pch=16,cex=0.5, main="Blue Plaques in Harrow")
plot(quadratcount(BluePlaquesSub.ppp, nx = 6, ny = 6),add=T,col="red")
Qcount<-data.frame(quadratcount(BluePlaquesSub.ppp, nx = 6, ny = 6))
QCountTable <- data.frame(table(Qcount$Freq, exclude=NULL))
QCountTable
QCountTable <- QCountTable[-nrow(QCountTable),]
class(QCountTable[,1])
vect<- as.numeric(levels(QCountTable[,1]))
vect <- vect[1:6]
QCountTable[,1] <- vect
QCountTable$total <- QCountTable[,1]*QCountTable[,2]
sums <- colSums(QCountTable[,-1])
sums
lambda <- sums[2]/sums[1]
QCountTable$Pr <- ((lambda^QCountTable[,1])*exp(-lambda))/factorial(QCountTable[,1])
QCountTable$Expected <- round(QCountTable$Pr * sums[1],0)
QCountTablplot(c(1,5),c(0,14), type="n", xlab="Number of Blue Plaques (Red=Observed, Blue=Expected)", ylab="Frequency of Occurances")
teststats <- quadrat.test(BluePlaquesSub.ppp, nx = 6, ny = 6)
teststats
plot(BluePlaquesSub.ppp,pch=16,cex=0.5, main="Blue Plaques in Harrow")
plot(teststats, add=T, col = "red")
K <- Kest(BluePlaquesSub.ppp, correction="border")
plot(K)
install.packages("fpc")
library(raster)
library(fpc)
library(plyr)
library(OpenStreetMap)
crs(Borough)
BluePlaquesSubPoints <- data.frame(BluePlaquesSub@coords[,1:2])
db <- fpc::dbscan(BluePlaquesSubPoints, eps = 700, MinPts = 4)
plot(db, BluePlaquesSubPoints, main = "DBSCAN Output", frame = F)
plot(Borough, add=T)
install.packages("ggplot2")
library(ggplot2)
db
db$cluster
BluePlaquesSubPoints$cluster <- db$cluster
chulls <- ddply(BluePlaquesSubPoints, .(cluster), function(df) df[chull(df$coords.x1, df$coords.x2), ])
chulls <- subset(chulls, cluster>=1)
dbplot <- ggplot(data=BluePlaquesSubPoints, aes(coords.x1,coords.x2, colour=cluster, fill=cluster)) 
dbplot <- dbplot + geom_point()
dbplot <- dbplot + geom_polygon(data = chulls, aes(coords.x1,coords.x2, group=cluster), alpha = 0.5) 
dbplot + theme_bw() + coord_equal()
latlong <- "+init=epsg:4326" 
BoroughWGS <-spTransform(Borough, CRS(latlong))
BoroughWGS@bbox
basemap<-openmap(c(51.5530613,-0.4040719),c(51.6405318,-0.2671556), zoom=NULL,"stamen-toner")
basemap_bng<-openproj(basemap, projection=BNG)
autoplot(basemap_bng) + geom_point(data=BluePlaquesSubPoints, aes(coords.x1,coords.x2, colour=cluster, fill=cluster)) + geom_polygon(data = chulls, aes(coords.x1,coords.x2, group=cluster, fill=cluster), alpha = 0.5)  
library(rgdal)
LondonWards <- readOGR("LondonWardData/LondonWards.shp", layer="LondonWards")
proj4string(LondonWards) <- CRS("+init=epsg:27700")
tmap_mode("view")
tm_shape(LondonWards) +
  tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(BluePlaques) +
  tm_dots(col = "blue")
summary(BluePlaquesBNG)
BluePlaquesSub <- BluePlaquesBNG[LondonWards,]
tm_shape(LondonWards) +
  tm_polygons(col = NA, alpha = 0.5) +
  tm_shape(BluePlaquesSub) +
  tm_dots(col = "blue")
res <- poly.counts(BluePlaquesSub, LondonWards)
LondonWards@data$BluePlaqueCount<-res
LondonWards@data$BlueDensity <- LondonWards$BluePlaqueCount/poly.areas(LondonWards)
LondonWards@data
tm_shape(LondonWards) +
  tm_polygons("BlueDensity",
              style="jenks",
              palette="PuOr",
              midpoint=NA,
              title="Blue Plaque Density")
library(spdep)
install.packages('spdep')
coordsW <- coordinates(LondonWards)
plot(coordsW)
LWard_nb <- poly2nb(LondonWards, queen=T)
plot(LWard_nb, coordinates(coordsW), col="red")
plot(LondonWards, add=T)
Lward.lw <- nb2listw(LWard_nb, style="C")
head(Lward.lw$neighbours)
I_LWard_Global_Density <- moran.test(LondonWards@data$BlueDensity, Lward.lw)
I_LWard_Global_Density
C_LWard_Global_Density <- geary.test(LondonWards@data$BlueDensity, Lward.lw)
C_LWard_Global_Density
G_LWard_Global_Density <- globalG.test(LondonWards@data$BlueDensity, Lward.lw)
G_LWard_Global_Density
I_LWard_Local <- localmoran(LondonWards@data$BluePlaqueCount, Lward.lw)
I_LWard_Local_Density <- localmoran(LondonWards@data$BlueDensity, Lward.lw)
head(I_LWard_Local_Density)
LondonWards@data$BLocI <- I_LWard_Local[,1]
LondonWards@data$BLocIz <- I_LWard_Local[,4]
LondonWards@data$BLocIR <- I_LWard_Local_Density[,1]
LondonWards@data$BLocIRz <- I_LWard_Local_Density[,4]
breaks1<-c(-1000,-2.58,-1.96,-1.65,1.65,1.96,2.58,1000)
MoranColours<- rev(brewer.pal(8, "RdGy"))
tm_shape(LondonWards) +
  tm_polygons("BLocIRz",
              style="fixed",
              breaks=breaks1,
              palette=MoranColours,
              midpoint=NA,
              title="Local Moran's I, Blue Plaques in London")
Gi_LWard_Local_Density <- localG(LondonWards@data$BlueDensity, Lward.lw)
head(Gi_LWard_Local_Density)
I_LWard_Local_GCSE <- localmoran(LondonWards@data$AvgGCSE201, Lward.lw)
LondonWards@data$GCSE_LocIz <- I_LWard_Local_GCSE[,4]
tm_shape(LondonWards) +
  tm_polygons("GCSE_LocIz",
              style="fixed",
              breaks=breaks1,
              palette=MoranColours,
              midpoint=NA,
              title="Local Moran's I, GCSE Scores")
Gi_LWard_Local_GCSE <- localG(LondonWards@data$AvgGCSE201, Lward.lw)
LondonWards@data$GCSE_LocGiz <- Gi_LWard_Local_GCSE
tm_shape(LondonWards) +
  tm_polygons("GCSE_LocGiz",
              style="fixed",
              breaks=breaks1,
              palette=GIColours,
              midpoint=NA,
              title="Gi*, GCSE Scores")